from pddl.heuristic import Heuristic


class LLMGeneratedHeuristic(Heuristic):
    """
    Blocksworld heuristic generated by an LLM and cleaned for syntax.

    It counts:
    - unsatisfied positive goals
    - violated negative goals

    and returns their sum as a non-negative float.
    """

    def __init__(self, stats=None):
        super().__init__(
            is_safe=True,
            is_goal_aware=True,
            is_consistent=True,
            stats=stats,
        )

    def h(self, actions, initial_state, goal, parent_node=None) -> float:
        positive_goals, negative_goals = goal

        # Count how many positive goals are not yet satisfied in the current state
        unsatisfied_positive = sum(1 for g in positive_goals if g not in initial_state)

        # Count how many negative goals are violated in the current state
        violated_negative = sum(1 for g in negative_goals if g in initial_state)

        # Heuristic value: total number of unsatisfied positive goals plus violated negatives
        return float(unsatisfied_positive + violated_negative)
