#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ast
import os
from pathlib import Path
from typing import Optional

from openai import OpenAI
import textwrap

# -------- Placeholder (fallback) --------

PLACEHOLDER_BODY = """\
from pddl.heuristic import Heuristic


class LLMGeneratedHeuristic(Heuristic):
    \"""
    Domain-specific heuristic generated by an LLM (placeholder version).
    Currently just wraps a simple delete-relaxation-style idea:
    - count number of unsatisfied positive goals in the current state.
    \"""


    def __init__(self, stats=None):
        super().__init__(is_safe=True, is_goal_aware=True,
                         is_consistent=True, stats=stats)


    def h(self, actions, initial_state, goal, parent_node=None):
        positive_g, negative_g = goal
        unsatisfied = [g for g in positive_g if g not in initial_state]
        return float(len(unsatisfied))
"""

# -------- Prompt --------

PROMPT_TEMPLATE = """\
You are helping with a classical planning project.

We have a PDDL domain called "{domain_name}".
Below is (a fragment of) its PDDL domain file:

--- BEGIN PDDL ---
{pddl_snippet}
--- END PDDL ---

Write a Python heuristic class called LLMGeneratedHeuristic that subclasses
pddl.heuristic.Heuristic and implements:

    def h(self, actions, initial_state, goal, parent_node=None) -> float

Requirements:
- 'actions' is a collection of grounded pddl.action.Action objects.
- 'initial_state' is a frozenset of ground atoms (tuples).
- 'goal' is a pair (positive_goals, negative_goals), each a frozenset of atoms.
- Return a non-negative float heuristic value.
- The heuristic must be safe: must not raise exceptions.
- Prefer simple, efficient logic that uses the domain structure.
- Only use the Python standard library.

Return only valid Python code for LLMGeneratedHeuristic, nothing else.
"""


def build_prompt(domain_name: str, domain_pddl: Path | None) -> str:
    if domain_pddl is not None and domain_pddl.exists():
        text = domain_pddl.read_text()
        snippet = text[:2000]
    else:
        snippet = "// PDDL file not provided"
    return PROMPT_TEMPLATE.format(domain_name=domain_name, pddl_snippet=snippet)

# -------- LLM hook --------

DEFAULT_MODEL = os.environ.get("LLM_HEURISTIC_MODEL", "gpt-4.1-mini")


def call_llm_api(prompt: str, *, model: Optional[str] = None) -> str:
    model = model or DEFAULT_MODEL
    client = OpenAI()

    resp = client.responses.create(
        model=model,
        input=prompt,
        max_output_tokens=800,
        temperature=0.2,
    )

    # v1 Responses: first output -> first content -> text (string)
    return resp.output[0].content[0].text.strip()

# -------- Safety (minimal) --------

def is_code_safe(source: str) -> bool:
    try:
        tree = ast.parse(source)
    except SyntaxError as e:
        print(f"[generate_heuristic] Syntax error in generated code: {e}")
        return False

    has_class = False
    has_h = False
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef) and node.name == "LLMGeneratedHeuristic":
            has_class = True
            for b in node.body:
                if isinstance(b, ast.FunctionDef) and b.name == "h":
                    has_h = True

    if not has_class:
        print("[generate_heuristic] No LLMGeneratedHeuristic class found")
    if not has_h:
        print("[generate_heuristic] No h method found")

    return has_class and has_h

# -------- Main generation --------

def generate_code_or_fallback(prompt: str) -> str:
    raw = call_llm_api(prompt)
    # Always write the raw output; do NOT parse or check.
    return str(raw)


def main(
    domain_name: str,
    domain_pddl_path: str | None,
    out_dir: str = "llm",
    candidate_id: int | None = None,
) -> None:
    domain_pddl = Path(domain_pddl_path) if domain_pddl_path else None
    prompt = build_prompt(domain_name, domain_pddl)

    out_dir_path = Path(out_dir)
    out_dir_path.mkdir(exist_ok=True, parents=True)

    if candidate_id is None:
        filename = f"{domain_name}_heuristic.py"
    else:
        filename = f"{domain_name}_heuristic_candidate_{candidate_id}.py"

    out_path = out_dir_path / filename

    code = generate_code_or_fallback(prompt)
    out_path.write_text(code)

    print(f"[generate_heuristic] Domain: {domain_name}")
    print(f"[generate_heuristic] Prompt (first 400 chars):")
    print(prompt[:400].replace("\\n", " ") + "...")
    print(f"[generate_heuristic] Wrote heuristic to {out_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--domain-name", required=True)
    parser.add_argument("--domain-pddl", required=False)
    parser.add_argument("--out-dir", default="llm")
    parser.add_argument("--candidate-id", type=int, default=None)
    args = parser.parse_args()
    main(
        domain_name=args.domain_name,
        domain_pddl_path=args.domain_pddl,
        out_dir=args.out_dir,
        candidate_id=args.candidate_id,
    )
