from pddl.heuristic import Heuristic


class LLMGeneratedHeuristic(Heuristic):
    """
    Logistics heuristic generated by an LLM and cleaned for syntax.

    Returns the number of unsatisfied positive goals in the current state
    as a simple, safe estimate of goal distance.
    """

    def __init__(self, stats=None):
        super().__init__(
            is_safe=True,
            is_goal_aware=True,
            is_consistent=True,
            stats=stats,
        )

    def h(self, actions, initial_state, goal, parent_node=None) -> float:
        positive_goals, negative_goals = goal

        # Count how many positive goals are not yet satisfied in the current state
        unsatisfied = 0
        for atom in positive_goals:
            if atom not in initial_state:
                unsatisfied += 1

        # Negative goals ignored for simplicity and safety

        return float(unsatisfied)
