#!/usr/bin/env python3

"""
Miconic-STRIPS Problem Generator (Python Version)
Generated by an LLM and adapted by @meneguzzi
Original domain: Typed STRIPS, AIPS-2000 competition
https://github.com/AI-Planning/pddl-generators/tree/main/miconic
Options:
  -f <num> : number of floors (minimum 2)
  -p <num> : number of passengers (minimum 1)
  -r <num> : optional random seed

Passenger types:
- going_up / going_down
- vip
- going_nonstop
- attendant
- never_alone
- conflict_A / conflict_B
- no_access

Output: PDDL problem file for the Miconic domain
"""

import random
import math
import argparse
import shutil
from collections import defaultdict
from datetime import datetime


class MiconicProblemGenerator:
    DOMAIN = "generators/miconic/domain.pddl"

    def __init__(self, floors, passengers, seed=None):
        assert floors >= 2, "Must have at least 2 floors"
        assert passengers >= 1, "Must have at least 1 passenger"

        self.floors = floors
        self.passengers = passengers
        self.seed = seed or int(datetime.now().timestamp() * 1000000)
        # random.seed(self.seed)
        self.rng = random.Random(self.seed)

        self.origins = [None] * passengers
        self.destinations = [None] * passengers

        self.types = defaultdict(set)  # going_up, going_down, vip, etc.
        self.no_access = defaultdict(set)

    def generate(self, format, goalsPerProblem, problem_index, output):
        self._assign_passenger_types()
        self._generate_journeys()
        self._generate_no_access()
        return self._to_pddl(format, goalsPerProblem, problem_index, output)

    def _assign_passenger_types(self):
        p = self.passengers

        def pick_unique(n, exclude):
            s = set()
            while len(s) < n:
                cand = self.rng.randint(0, p - 1)
                if cand in exclude:
                    continue
                s.add(cand)
            return list(s)

        percent = lambda n: int(self.passengers * (n / 100))

        # Preset type distributions
        ratios = {
            'up_down': 30,
            'vip': 15,
            'going_nonstop': 10,
            'never_alone': 10,
            'attendant': 10,
            'con_A': 10,
            'con_B': 10,
            'no_access': 10
        }

        # Assign types avoiding overlap where needed
        assigned = set()
        self.types['up_down'] = set(pick_unique(percent(ratios['up_down']), assigned))
        assigned.update(self.types['up_down'])

        self.types['vip'] = set(pick_unique(percent(ratios['vip']), assigned))
        assigned.update(self.types['vip'])

        self.types['going_nonstop'] = set(pick_unique(percent(ratios['going_nonstop']), assigned))
        assigned.update(self.types['going_nonstop'])

        self.types['never_alone'] = set(pick_unique(percent(ratios['never_alone']), assigned))
        assigned.update(self.types['never_alone'])

        if self.types['never_alone']:
            self.types['attendant'] = set(pick_unique(max(1, percent(ratios['attendant'])), assigned.union(self.types['never_alone'])))
            assigned.update(self.types['attendant'])

        self.types['con_A'] = set(pick_unique(percent(ratios['con_A']), assigned))
        assigned.update(self.types['con_A'])

        if self.types['con_A']:
            self.types['con_B'] = set(pick_unique(percent(ratios['con_B']), assigned.union(self.types['con_A'])))
            assigned.update(self.types['con_B'])

        self.types['no_access'] = set(pick_unique(percent(ratios['no_access']), assigned))

        # Untyped
        all_ids = set(range(self.passengers))
        self.types['untyped'] = all_ids - set().union(*self.types.values())

    def _generate_journeys(self):
        for i in range(self.passengers):
            while True:
                origin = self.rng.randint(0, self.floors - 1)
                # Constraint checks omitted for brevity
                self.origins[i] = origin
                break

            while True:
                destin = self.rng.randint(0, self.floors - 1)
                if destin == origin:
                    continue
                # Constraint checks omitted for brevity
                self.destinations[i] = destin
                break

        # Determine direction
        for i in self.types['up_down']:
            if self.origins[i] < self.destinations[i]:
                self.types['going_up'].add(i)
            else:
                self.types['going_down'].add(i)

    def _generate_no_access(self):
        for p in self.types['no_access']:
            for f in range(self.floors):
                if f == self.origins[p] or f == self.destinations[p]:
                    continue
                if self.rng.randint(0, 99) < 30:  # 30% chance
                    self.no_access[p].add(f)

    def _to_pddl(self, format, goalsPerProblem, problem, output_folder):
        lines = [f"(define (problem miconic-f{self.floors}-p{self.passengers})",
                 "  (:domain miconic)",
                 "  (:objects"]

        lines.append("    " + " ".join(f"p{i}" for i in range(self.passengers)) + " - passenger")
        lines.append("    " + " ".join(f"f{i}" for i in range(self.floors)) + " - floor")
        lines.append("  )")

        lines.append("  (:init")
        for i in range(self.floors):
            for j in range(i + 1, self.floors):
                lines.append(f"    (above f{i} f{j})")
        for i in range(self.passengers):
            lines.append(f"    (origin p{i} f{self.origins[i]})")
            lines.append(f"    (destin p{i} f{self.destinations[i]})")
        for p, fs in self.no_access.items():
            for f in fs:
                lines.append(f"    (no-access p{p} f{f})")
        lines.append("    (lift-at f0)")
        lines.append("  )")

        generate_intention_pddl = False
        generate_pddl = False

        if format == 'intention':
            generate_intention_pddl = True
        elif format == 'pddl':
            generate_pddl = True
        elif format == 'both':
            generate_pddl = generate_intention_pddl = True

        pddl_lines = lines[:]

        if generate_pddl:
            pddl_lines.append("  (:goal")
            pddl_lines.append("    (and")
            for i in range(self.passengers):
                pddl_lines.append(f"      (served p{i})")
            pddl_lines.append("    )")
            pddl_lines.append("  )")
            pddl_lines.append(")")

            if output_folder is None:
                print("\n".join(pddl_lines))
            else:
                instanceFile = output_folder+"/pb%s.pddl" % problem
                with open(instanceFile, 'w', encoding='UTF-8') as outstream:
                    outstream.write("\n".join(pddl_lines))

        if generate_intention_pddl:
            lines.append("  (:desires")
            pps = math.ceil(self.passengers / goalsPerProblem)  # Passengers per problem
            for d in range(math.ceil(self.passengers / pps)):
                lines.append("(:desire    (and")
                for i in range(d*pps, min(d*pps + pps, self.passengers)):
                    lines.append(f"      (served p{i})")
                lines.append("   ) )")
            lines.append("  )")
            lines.append(")")

            if output_folder is None:
                print("\n".join(lines))
            else:
                instanceFile = output_folder+"/pb%si.pddl" % problem
                with open(instanceFile, 'w', encoding='UTF-8') as outstream:
                    outstream.write("\n".join(lines))


def main(argv):
    parser = argparse.ArgumentParser(description="Miconic PDDL Generator")
    parser.add_argument('output', help='Path to output folder')
    parser.add_argument("-f", type=int, default=None, required=False, help="Number of floors (min 2)")
    # parser.add_argument("-p", type=int, required=True, help="Number of passengers (min 1)")
    parser.add_argument("-fp", type=int, required=True, help="Starting Number of passengers (min 1)")
    parser.add_argument("-tp", type=int, required=True, help="Finishing Number of passengers (min 1)")
    parser.add_argument("-r", type=int, default=None, help="Random seed (optional)")
    parser.add_argument('-i', '--incrementalGoals', action='store_true', help='Whether multiple goals are incremental (for intention planning)')
    parser.add_argument('-v', '--verbose', action='store_true')
    parser.add_argument('-g', '--goalsPerProblem', default='2', type=int, help='Number of sub goals per problem (for intention planning)')
    parser.add_argument('-o', '--format', choices=['pddl', 'intention', 'both'], default="pddl", help='The format of the resulting problems')
    args = parser.parse_args(argv[1:])
    if args.output == '-':
        args.output = None

    # generator = MiconicProblemGenerator(args.f, args.p, args.r)
    # generator.generate(args.format, args.goalsPerProblem, 1, args.output)

    for p in range(args.fp, args.tp):
        if args.f is None:
            floors = p*2
        else:
            floors = args.f
        generator = MiconicProblemGenerator(floors, p, args.r)
        generator.generate(args.format, args.goalsPerProblem, p, args.output)

    if args.output is not None:
        shutil.copy(MiconicProblemGenerator.DOMAIN, args.output+"/domain.pddl")


if __name__ == "__main__":  # pragma: no cover
    import sys
    try:
        main(sys.argv)
    except Exception as e:
        print(e)
        sys.exit(-1)
