; [pycodestyle]
; count = False
; ignore = E128
; max-line-length = 160
; statistics = True

; [pytest]
; pythonpath = . simplafy
;Uncomment before committing to avoid wasting Github time
; timeout = 200
; filterwarnings = 
;     error
;     ignore::DeprecationWarning

[testenv]
deps = unittest
commands = unittest discover []

[flake8]
extend-ignore = E203, E701
exclude =
    .git,
    __pycache__
max-complexity = 12
max-line-length = 160
statistics = True
timeout = 100

[coverage:report]
omit = src/tests/*
; Regexes for lines to exclude from consideration
exclude_also =
    ; Don't complain about missing debug-only code:
    def __repr__
    if self\.debug

    ; Don't complain if tests don't hit defensive assertion code:
    raise AssertionError
    raise NotImplementedError

    ; Don't complain if non-runnable code isn't run:
    ; if 0:
    ; if __name__ == .__main__.:

    ; Don't complain about abstract methods, they aren't run:
    @(abc\.)?abstractmethod

; ignore_errors = True