(define (problem pb1)
  (:domain blocksworld)
  (:objects a b c)
  (:init (onTable a) (onTable b) (onTable c) 
         (clear a) (clear b) (clear c) 
         (equal a a) (equal b b) (equal c c) (handempty))
  (:desires (:desire (on a b))
            (:desire (on c a))
  ))